### ISSUE TITLE
Library doesn't use timeout in all requests library function calls

### ISSUE THREAD

**Issue by ethangrinnell78** [falkowich/pyise-ers#154]
This library doesn't include the timeout attribute when self.ise.get() is called. Timeout is only used for self.ise.request() in  the internal _request() function. That function also includes an earlier call to self.ise.get() without a timeout before calling self.ise.request() with a timeout. Thus, the configured timeout seldom has any effect that I have seen.

The argument "timeout=self.timeout" should be added to every self.ise.get() call

**Comment by falkowich** [comment]
Hi,
I
f you want to I am really thankful for help :)
So if you have an idea or anything already done, please send a PR over.

For the moment I can't commit to this, but I will put this in the famous ToDo :)

--
Regards Falk

**Comment by ethangrinnell78** [comment]
Done but not tested. Do you want me submit a PR into a specific branch?

**Comment by falkowich** [comment]
Hi, 

I have synced up dev now.
It would be great if you could make the PR to dev?

--
Regars Falk

**Comment by ethangrinnell78** [comment]
Submitted a PR to dev.

I commented in the request, timeouts used to be there in older code but were removed in the latest release. Also, I broke the changes into 2 commits. One adds timeouts and the other does some reformatting. Just in case you don't like the formatting changes.

**Comment by falkowich** [comment]
I will check this out as soon as #164 is done

And I am sorry for taking so much time with this..

--
Regards Falk

**Comment by falkowich** [comment]
Thanks!

Merged and tested in https://github.com/falkowich/pyise-ers/pull/174.  
Timeouts are now included.

--
Regards Falk
