### ISSUE TITLE
Add filter to get_device_groups

### ISSUE THREAD

**Issue by Kosire** [falkowich/pyise-ers#218]
**get_device_groups** should support the **filter** variable.
Cisco ISE supports contains and ncontains as filters.
`Searching for Network Device Groups by name, can only use the 'contains' or 'ncontains' filters`

`def get_device_groups(self, filter=None):
        """
        Get a list tuples of device groups.

        :return:
        """
        return self._get_groups(
            "{0}/config/networkdevicegroup".format(self.url_base),
            filter=filter
        )`

**Comment by falkowich** [comment]
_(copy paste from my last message to you_) :)
Hi,

Thanks for the code!
Is it possible that you can and/or have the time to do a PR?

If not, I'll create a PR myself with the changes.
Again, thanks for the help :)

--
Kind Regards Falk

**Comment by Kosire** [comment]
Merged in PR #222
